#====Faca um programa que leia um número inteiro e mostre na tela seu sucessor e seu antecessor ====

#====CRIE UM ALGORITIMO QUE LEIA UM NUMERO E MOSTRE SEU DOBRO SEU TRIPLO E A SUA RAIZ QUADRADA====

#====Desenvolva um programa que leia duas notas de um aluno, calcule e mostre a média entre elas====

#====ESCREVA UM PROGRAMA QUE LEIA UM VALOR EM METROS E O EXIBA CONVERTIDO EM CENTIMETROS E MILIMETROS====

#====FAÇA UM PROGRAMA QUE LEIA UM NUMERO INTEIRO QUALQUER E EXIBA NA TELA A SUA TABUADA====

#====CRIE UM PROGRAMA QUE LEIA QUANTO DINHEIRO UMA PESSSOA TEM NA CARTEIRA E MOSTRE QUANTOS DÓLARES ELA PODE COMRPAR. CONSIDERE US$1,00 = R$3,27====



